import { exerciseImageUrl } from "./assetPaths";

const manuscriptImages: Record<string, string> = {
  "hip-thrust": "/manus-storage/hip-thrust_80b089d1.gif",
  "elevacao-pelvica": "/manus-storage/elevacao-pelvica_ac7b41a5.gif",
  "glute-bridge": "/manus-storage/glute-bridge_d7364c5f.gif",
  coice: "/manus-storage/coice_0b326a3a.gif",
  abducao: "/manus-storage/abducao_dc306907.gif",
  "agachamento-sumo": "/manus-storage/agachamento-sumo_2adf4d00.gif",
  agachamento: "/manus-storage/agachamento_5569ce45.gif",
  "leg-press": "/manus-storage/leg-press_c59660bd.gif",
  hack: "/manus-storage/hack_36dd6128.gif",
  extensora: "/manus-storage/extensora_34e09ad1.gif",
  flexora: "/manus-storage/flexora_dce1fa38.gif",
  stiff: "/manus-storage/stiff_fe027d90.gif",
  afundo: "/manus-storage/afundo_4f017c1d.gif",
  passada: "/manus-storage/passada_247a423f.gif",
  panturrilha: "/manus-storage/panturrilha_534441a8.gif",
  "puxada-frontal": "/manus-storage/puxada-frontal_6017098e.gif",
  "remada-baixa": "/manus-storage/remada-baixa_31fcefb2.gif",
  "remada-unilateral": "/manus-storage/remada-unilateral_feb98070.gif",
  "remada-curvada": "/manus-storage/remada-curvada_6ccfb294.gif",
  supino: "/manus-storage/supino_e6b3ecc2.gif",
  crucifixo: "/manus-storage/crucifixo_543e626f.gif",
  crossover: "/manus-storage/crossover_69def2fc.gif",
  "elevacao-lateral": "/manus-storage/elevacao-lateral_ccfa6019.gif",
  "elevacao-frontal": "/manus-storage/elevacao-frontal_08df8760.gif",
  desenvolvimento: "/manus-storage/desenvolvimento_4e6de706.gif",
  "rosca-direta": "/manus-storage/rosca-direta_e0362fa3.gif",
  "rosca-alternada": "/manus-storage/rosca-alternada_99315757.gif",
  "rosca-martelo": "/manus-storage/rosca-martelo_72efb3c1.gif",
  "triceps-pulley": "/manus-storage/triceps-pulley_70dedd2a.gif",
  "triceps-frances": "/manus-storage/triceps-frances_2fc9f5f7.gif",
  "triceps-testa": "/manus-storage/triceps-testa_2e3d3ded.gif",
  abdominal: "/manus-storage/abdominal_41ec89d4.gif",
  prancha: "/manus-storage/prancha_ab4633a6.gif",
  "elevacao-pernas": "/manus-storage/elevacao-pernas_2059e679.gif",
};

export const EXERCISE_IMAGES: Record<string, string> = Object.fromEntries(
  Object.entries(manuscriptImages).map(([key, url]) => [key, exerciseImageUrl(key, url)]),
);
