import { exerciseImageUrl } from "./assetPaths";

const manuscriptImages: Record<string, string> = {
  "hip-thrust": "/manus-storage/hip-thrust_80b089d1.gif",
  "elevacao-pelvica": "/manus-storage/elevacao-pelvica_ac7b41a5.gif",
  "glute-bridge": "/manus-storage/glute-bridge_d7364c5f.gif",
  coice: "/manus-storage/coice_0b326a3a.gif",
  abducao: "/manus-storage/abducao_dc306907.gif",
  "agachamento-sumo": "/manus-storage/agachamento-sumo_2adf4d00.gif",
  agachamento: "/manus-storage/agachamento_5569ce45.gif",
  "leg-press": "/manus-storage/leg-press_c59660bd.gif",
  hack: "/manus-storage/hack_36dd6128.gif",
  extensora: "/manus-storage/extensora_34e09ad1.gif",
  flexora: "/manus-storage/flexora_dce1fa38.gif",
  stiff: "/manus-storage/stiff_fe027d90.gif",
  afundo: "/manus-storage/afundo_4f017c1d.gif",
  passada: "/manus-storage/passada_247a423f.gif",
  panturrilha: "/manus-storage/panturrilha_534441a8.gif",
  "puxada-frontal": "/manus-storage/puxada-frontal_6017098e.gif",
  "remada-baixa": "/manus-storage/remada-baixa_31fcefb2.gif",
  "remada-unilateral": "/manus-storage/remada-unilateral_feb98070.gif",
  "remada-curvada": "/manus-storage/remada-curvada_6ccfb294.gif",
  supino: "/manus-storage/supino_e6b3ecc2.gif",
  crucifixo: "/manus-storage/crucifixo_543e626f.gif",
  crossover: "/manus-storage/crossover_69def2fc.gif",
  "elevacao-lateral": "/manus-storage/elevacao-lateral_ccfa6019.gif",
  "elevacao-frontal": "/manus-storage/elevacao-frontal_08df8760.gif",
  desenvolvimento: "/manus-storage/desenvolvimento_4e6de706.gif",
  "rosca-direta": "/manus-storage/rosca-direta_e0362fa3.gif",
  "rosca-alternada": "/manus-storage/rosca-alternada_99315757.gif",
  "rosca-martelo": "/manus-storage/rosca-martelo_72efb3c1.gif",
  "triceps-pulley": "/manus-storage/triceps-pulley_70dedd2a.gif",
  "triceps-frances": "/manus-storage/triceps-frances_2fc9f5f7.gif",
  "triceps-testa": "/manus-storage/triceps-testa_2e3d3ded.gif",
  abdominal: "/manus-storage/abdominal_41ec89d4.gif",
  prancha: "/manus-storage/prancha_ab4633a6.gif",
  "elevacao-pernas": "/manus-storage/elevacao-pernas_2059e679.gif",
  "levantamento-terra": "/media/exercises/levantamento-terra.gif",
  flexao: "/media/exercises/flexao.gif",
  "barra-fixa": "/media/exercises/barra-fixa.gif",
  polichinelo: "/media/exercises/polichinelo.gif",

  // Wikimedia Commons: demonstrações em GIF com licenças verificáveis.
  "agachamento-frontal": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Zecher-squats-2.gif",
  "step-up": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Step_up-CDC_strength_training_for_older_adults.gif",
  "flexao-inclinada": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Pushups_wbs.gif",
  "abdominal-sit-up": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Situps.gif",
  "agachamento-unilateral": "https://commons.wikimedia.org/wiki/Special:Redirect/file/One-leg-squat-1.gif",

  // Novos GIFs para exercícios que estavam sem demonstração.
  "panturrilha-sentado": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Seated-calf-raise-1.gif",
  "panturrilha-unilateral": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Seated-one-leg-calf-raise-2.gif",
  "triceps-corda": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Triceps-pushdown-with-rope-1.gif",
  "rosca-scott": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Biceps-curl-CDC_strength_training_for_older_adults.gif",
  "rosca-cabo": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Biceps-curl-CDC_strength_training_for_older_adults.gif",
  "rosca-elastico": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Biceps-curl-CDC_strength_training_for_older_adults.gif",
  "triceps-coice": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Triceps-extensions-1.gif",
  "supino-maquina": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Chest_press-CDC_strength_training_for_older_adults.gif",
  "desenvolvimento-maquina": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Shoulder_press_-_exercise_demonstration_video.webm",
  "elevacao-lateral-cabo": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Standing-lateral-raise-1.gif",
  "supino-inclinado": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Incline-chest-press-1.gif",
  "mesa-flexora": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Lying-leg-curl-1.gif",
  "agachamento-goblet": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Kettlebell_Goblet_Squat.webm",
  "good-morning": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Good-morning-1.gif",
  "terra-sumo": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Deadlift-1.gif",
  "remada-maquina": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Seated-row-1.gif",
  "puxada-neutra": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Lat-pulldown-1.gif",
  "encolhimento": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Barbell-shrug-1.gif",
  "posterior-maquina": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Reverse-fly-1.gif",
  "crucifixo-maquina": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Chest-fly-1.gif",
  "mergulho-banco": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Bench-dips-1.gif",
  "abdominal-cabo": "/manus-storage/abdominal_41ec89d4.gif",
  "abdominal-roda": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Ab-wheel-1.gif",
  "prancha-lateral": "/manus-storage/prancha_ab4633a6.gif",
  "dead-bug": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Dead-bug-1.gif",
  "bird-dog": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Bird-dog-1.gif",
  "mountain-climber": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Mountain-climber-1.gif",
  "kickback-elastico": "/manus-storage/coice_0b326a3a.gif",
  "abducao-elastico": "/manus-storage/abducao_dc306907.gif",
  "glute-bridge-elastico": "/manus-storage/glute-bridge_d7364c5f.gif",
  "agachamento-bulgaro": "https://commons.wikimedia.org/wiki/Special:Redirect/file/One-leg-squat-1.gif",
  "caminhada-elastico": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Lateral-band-walk-1.gif",
  "levantamento-lateral-caneleira": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Side-lying-leg-raise-1.gif",
};

export const EXERCISE_IMAGES: Record<string, string> = Object.fromEntries(
  Object.entries(manuscriptImages).map(([key, url]) => [key, exerciseImageUrl(key, url)]),
);
